mercado/app/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path('detalle/<int:pk>/', views.Detalle.as_view(), name="detalle"),

    #Admin
    path('admin/listar/', views.ListarAdmin.as_view(), name="admin_listar"),
    path('admin/nuevo/', views.NuevoAdmin.as_view(), name="admin_nuevo"),
    path('admin/editar/<int:pk>/', views.EditarAdmin.as_view(), name="admin_editar"),

    path('MisProductos', views.MisProductos.as_view(), name="mis_productos")
]

mercado/app/usuarios/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
    path('registrarme/', views.Registrarme.as_view(), name="registrarme"),

]

mercado/mercado/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', views.inicio, name="inicio"),
    path('', views.Inicio.as_view(), name="inicio"),

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.logout_then_login, name="logout"),

    #Includes
    path('producto/', include('app.productos.urls')),
    path('usuario/', include('app.usuarios.urls')),
    path('favoritos/', include('app.favoritos.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mercado/templates/inicio.html
{% extends "base/base.html" %}

<!-- {% load static %} SOLO SI ES NECESARIO -->

{% block contenido %}
  <h1>Ofertas del día</h1>
    <form class="form-inline my-2 my-lg-0" style="padding:50px;">
      <div class="row">
        <div class="col-md-10">
          <input class="form-control mr-sm-2" type="search" placeholder="Ingrese nombre del producto..." aria-label="Search">
        </div>
        <div class="col-md-2">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </div>
      </div>
    </form>


  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for p in productos %}
      <div class="col">
        <div class="card shadow-sm">
          {% if p.imagen %}
            <img src="{{p.imagen.url}}" alt="" class="bd-placeholder-img card-img-top" width="100%" height="225">
          {% else %}
          <!--poner una imagen personalizada:
          <img src="{% static 'images/default/nombre_de_la_imagen.jpg' %}" alt="" class="bd-placeholder-img card-img-top" width="100%" height="225">
        -->
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"></text></svg>
          {% endif %}
          <div class="card-body">
            <p class="card-text">
              {{p.nombre}}
              {% for c in p.categorias.all %}
              <span class="badge rounded-pill bg-primary">{{c.nombre}}</span>
              {% endfor %}

            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <!--<button type="button" class="btn btn-sm btn-outline-secondary">View</button>-->
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'productos:detalle' p.id %}">Ver más</a>

                {% include "productos/includes/show_estado.html" %}
                
              </div>
              <!--<small class="text-muted">9 mins</small>-->
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock contenido %}

mercado/templates/login.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Login</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
-->
<meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
</head>

<body class="text-center">
  <main class="form-signin">
    <form method="POST">{% csrf_token %}
      <!--
      <img class="mb-4" src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      -->
      <h1 class="h3 mb-3 fw-normal">Iniciar sesión</h1>
      <p>Página de práctica Mercado</p>

      {% include "includes/form_errors.html" %}

      <div class="form-floating">
        <input type="text" class="form-control" id="inputUsername" placeholder="Nombre de Usuario" autofocus="" name="username">
        <label for="inputUsername">Nombre de usuario</label>
      </div>

      <div class="form-floating">
        <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
        <label for="floatingPassword">Contraseña</label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Recuérdame
        </label>
      </div>

      <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>

      <p class="mt-5 mb-3 text-muted"><a href="{% url 'usuarios:registrarme' %}">Registrarme</a></p>

      <p class="mt-5 mb-3 text-muted"><a href="{% url 'inicio' %}">Ir al Inicio</a></p>

      <p class="mt-5 mb-3 text-muted">By CFK - dic/2021</p>
    </form>
  </main>
</body>
</html>