mercado/app/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path('detalle/<int:pk>/', views.Detalle.as_view(), name="detalle"),

    #Admin
    path('admin/listar/', views.ListarAdmin.as_view(), name="admin_listar"),
    path('admin/nuevo/', views.NuevoAdmin.as_view(), name="admin_nuevo"),
    path('admin/editar/<int:pk>/', views.EditarAdmin.as_view(), name="admin_editar"),

    path('MisProductos', views.MisProductos.as_view(), name="mis_productos")
]

mercado/mercado/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', views.inicio, name="inicio"),
    path('', views.Inicio.as_view(), name="inicio"),

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.logout_then_login, name="logout"),

    #Includes
    path('producto/', include('app.productos.urls')),
    path('usuario/', include('app.usuarios.urls')),
    path('favoritos/', include('app.favoritos.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mercado/app/productos/models.py
from django.db import models

from app.usuarios.models import Usuario


class Categoria(models.Model):
    nombre = models.CharField(max_length=250)

    class Meta:
        db_table="categorias"

    def __str__(self):
        return self.nombre

ESTADOS_CHOICES = (
    (1, "ACTIVO"),
    (2, "INACTIVO"),
    (3, "SIN STOCK")
)

class Producto(models.Model):
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField(default="")
    precio = models.DecimalField(max_digits=9, decimal_places=2)

    categorias = models.ManyToManyField(Categoria)

    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True)

    imagen = models.ImageField(upload_to="productos", null=True)

    estado = models.IntegerField(choices=ESTADOS_CHOICES, default=1)

    class Meta:
        db_table="productos"

    def __str__(self):
        return self.nombre

mercado/productos/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return self.nombre

mercado/app/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    nombre = forms.CharField(label="Nombre del Producto", widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Ingrese el nombre del producto"}))
    descripcion = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    # attrs={'cols':80, 'rows': 20} - DENTRO DEL PARENTESIS DEL TEXTAREA()

    class Meta:
        model = Producto
        fields = ["nombre", "precio", "categorias", "descripcion", "imagen", "estado"]

mercado/app/productos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

from app.core.mixins import AdminRequiredMixins

from django.urls import reverse_lazy
from .forms import ProductoForm
from .models import Producto

'''
def detalle(request):
    context = {}
    return render(request, "productos/detalle.html", context)
'''

class ListarAdmin(LoginRequiredMixin, AdminRequiredMixins, ListView):
    template_name="productos/admin/listar.html"
    model = Producto
    context_object_name="productos"
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(ListarAdmin, self).get_context_data(**kwargs)
        context["nombre_buscado"] = self.request.GET.get("nombre_producto", "")
        return context

    def get_queryset(self):
        busqueda_nombre = self.request.GET.get("nombre_producto", "")
        query = Producto.objects.all().order_by("nombre")
        if len(busqueda_nombre) > 0:
            query = query.filter(nombre__icontains=busqueda_nombre)
        return query


class MisProductos(LoginRequiredMixin, AdminRequiredMixins, ListView):
    template_name="productos/admin/listar.html"
    model = Producto
    context_object_name="productos"

    def get_queryset(self):
        self.request
        return Producto.objects.filter(usuario_id=self.request.user.id).order_by("id")



class NuevoAdmin(AdminRequiredMixins, CreateView):
    template_name = "productos/admin/nuevo.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

    def form_valid(self, form):
        f = form.save(commit=False)
        f.usuario_id = self.request.user.id
        return super(NuevoAdmin, self).form_valid(form)

class EditarAdmin(UpdateView):
    template_name = "productos/admin/editar.html"
    model = Producto
    form_class = ProductoForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:admin_listar")

class Detalle(DetailView):
    template_name = "productos/detalle.html"
    model = Producto

mercado/templates/productos/admin/editar.html
{% extends "base/base.html" %}

{% block contenido %}
  <form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {% include "includes/form_errors.html" %}

    {{form.as_p}}

    <div class="row">
      <div class="col">
        <button type="submit" class="btn btn-success">Guardar</button>
        <a href="{% url 'productos:admin_listar'%}" class="btn btn-danger">Cancelar</a>
      </div>

    </div>
  </form>

{% endblock contenido %}

mercado/templates/productos/admin/listar.html
{% extends "base/base.html" %}

{% block contenido %}
  <form class="form-inline my-2 my-lg-0" style="padding:50px;" method="GET">
    <div class="row">
      <div class="col-md-10">
        <input class="form-control mr-sm-2" name="nombre_producto" type="search" placeholder="Ingrese nombre del producto..." aria-label="Search" value="{{nombre_buscado}}">
      </div>
      <div class="col-md-2">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
      </div>
    </div>
  </form>

  <div class="row" style="padding: 10px">
    <div class="col">
      <a href="{% url 'productos:admin_nuevo'%}" class="btn btn-success">Nuevo</a>
    </div>
  </div>

  <table class="table table-success table-striped">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Nombre</th>
          <th scope="col">Precio</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for p in productos %}
          <tr>
            <th scope="row">{{p.id}}</th>
            <td>{{p.nombre}}</td>
            <td>$ {{p.precio}}</td>
            <td>
              <a href="#">Ver</a>
              <a href="{% url 'productos:admin_editar' p.id %}">Editar</a>
              <a href="#">Eliminar</a>
            </td>

          </tr>
        {% endfor %}
      </tbody>
  </table>

{% include "includes/paginador.html" %}

{% endblock contenido %}

mercado/templates/productos/admin/nuevo.html
{% extends "base/base.html" %}

{% block contenido %}
  <form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {% include "includes/form_errors.html" %}

    {{form.as_p}}

    <div class="row">
      <div class="col">
        <button type="submit" class="btn btn-success">Guardar</button>
        <a href="{% url 'productos:admin_listar'%}" class="btn btn-danger">Cancelar</a>
      </div>

    </div>
  </form>

{% endblock contenido %}