mercado/app/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path('detalle/<int:pk>/', views.Detalle.as_view(), name="detalle"),

    #Admin
    path('admin/listar/', views.ListarAdmin.as_view(), name="admin_listar"),
    path('admin/nuevo/', views.NuevoAdmin.as_view(), name="admin_nuevo"),
    path('admin/editar/<int:pk>/', views.EditarAdmin.as_view(), name="admin_editar"),

    path('MisProductos', views.MisProductos.as_view(), name="mis_productos")
]

mercado/mercado/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', views.inicio, name="inicio"),
    path('', views.Inicio.as_view(), name="inicio"),

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.logout_then_login, name="logout"),

    #Includes
    path('producto/', include('app.productos.urls')),
    path('usuario/', include('app.usuarios.urls')),
    path('favoritos/', include('app.favoritos.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mercado/templates/base/base.html
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>## Mercado ##</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">



    <!-- Bootstrap core CSS -->
    <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">



    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>

    {% include "base/header.html" %}

      <main>
        {% include "base/portada.html" %}

        <div class="album py-5 bg-light">
          <div class="container">
            {% block menu %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">MENU</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'inicio'%}">Inicio</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Catálogo</a>
                    </li>
                    {% if user.is_authenticated %}
                      
                      {% if user.es_administrador %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'productos:admin_listar' %}">Productos</a>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'productos:mis_productos' %}">Mis Productos</a>
                      {% endif %}
                    {% endif %}

                    </li>
                  </ul>
                </div>
              </div>
            </nav>
              {% endblock menu %}
            {% block contenido %}
              <h1>En el padre, sin redefinir el block</h1>
            {% endblock contenido %}
          </div>
        </div>

      </main>

{% include "base/footer.html" %}

<!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

mercado/templates/base/footer.html
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="{% url 'inicio'%}">Ir al Inicio</a>
    </p>
    <p class="mb-1">Sitio de práctica desarrollado durante el Informatorio 2021.</p>
  </div>
</footer>

mercado/templates/base/header.html
<header>
  <div class="bg-dark collapse" id="navbarHeader" style="">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Sobre Nosotros</h4>
          <p class="text-muted">Este es un sitio de compras que forma parte de mis prácticas en el Informatorio.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Opciones</h4>
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}" class="text-white">Cerrar sesión</a></li>
            {% else %}
              <li><a href="{% url 'login' %}" class="text-white">Iniciar sesión</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'inicio'%}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Mercado</strong>
      </a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

mercado/templates/base/portada.html
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Bienvenido al Mercado!</h1>
      <p class="lead text-muted">Pase y elija lo que quiera comprar. Encontrará gran variedad de artículos y ofertas.</p>
    <!--
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    -->
    </div>
  </div>
</section>